name: 'food-and-color-emoji-action'
description: 'Spits out an emoji based on input'
inputs:
  color:
    description: 'The color to return an emoji for'
    required: true
    default: 'green'
  food:
    description: 'The food to return an emoji for'
    required: true
    default: 'pizza'
outputs:
  color-emoji:
    description: "The color emoji"
    value: ${{ steps.color-emoji-generator.outputs.color-emoji }}
  food-emoji:
    description: "The food emoji"
    value: ${{ steps.food-emoji-generator.outputs.food-emoji }}
runs:
  using: "composite"
  steps:
    - id: color-emoji-generator
      shell: bash
      run: |
        echo "::debug::You entered ${{ inputs.color }}."
        
        case ${{ inputs.color }} in
          red)
            color=ðŸŽˆ ;;
          orange)
            color=ðŸŽƒ ;;
          yellow)
            color=ðŸ ;;
          green)
            color=ðŸ¸ ;;
          blue)
            color=ðŸ’™ ;;
          indigo)
            color=ðŸª ;;
          violet)
            color=ðŸª» ;;
          *)
            echo "You entered another color, ${{ inputs.color }}, so you get this emoji."
            color=ðŸŽ¨ ;;
        esac
        
        echo "color-emoji=$(echo $color)" >> $GITHUB_OUTPUT
        
    - id: food-emoji-generator
      shell: bash
      run: |
        echo "::debug::You entered ${{ inputs.color }}."
        case "${{ inputs.food }}" in
          "pad thai")
            food=ðŸœ ;;
          "pizza")
            food=ðŸ• ;;
          "burger")
            food=ðŸ” ;;
          "steak")
            food=ðŸ¥© ;;
          "fish")
            food=ðŸ£ ;;
          "shrimp")
            food=ðŸ¤ ;;
          "salad")
            food=ðŸ¥— ;;
          "donut")
            food=ðŸ© ;;
          "grapes")
            food=ðŸ‡ ;;
          "taco")
            food=ðŸŒ® ;;
          "egg")
            food=ðŸ³ ;;
          "cookie")
            food=ðŸª ;;
          "bacon")
            food=ðŸ¥“ ;;
          *)
            echo "You entered another food, ${{ inputs.food }}, so you get this emoji."
            food=ðŸ½ï¸
            ;;
        esac
        
        echo "food-emoji=$(echo $food)" >> $GITHUB_OUTPUT
