name: workflow-a

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Trigger Workflow
      uses: actions/github-script@v7
      with:
        script: |
          console.log("... logging values for debug ...");
          console.log(context.repo.owner);
          console.log(context.repo.repo);
          console.log(context.ref);
          console.log("...");
          
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.ref,
            workflow_id: 'workflow-b.yml',
            inputs: {
              "color": "orange",
              "food": "avocado",
              "animal": "bee",
            }
          })
