name: workflow-a

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Trigger Workflow
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'workflow-b.yml',
            ref: '${{ github.head_ref }}',
            inputs: {
              "color": "blue",
              "food": "pad thai",
            }
          })
